<nav role="left_navigation">
	<div id="leftPanel">
	  	<div class="toggleNav">Admin</div>
	  	<div class="leftNavContent0">
	  		<p><a href="http://www.noveltysoundbytes.com/blogOsphere/wp-login.php" target="_blank">blogOsphere</a></p>
	  		<p><a href="http://www2.netfirms.com/mail/index.bml?m=1" target="_blank">Webmail</a></p>
	  		<p><a href="https://secure.netfirms.com/secure/login.bml?err=" target="_blank">Netfirms</a></p>
	  		<p><a href="http://sakiwinki.com/pages/portfolio.html" target="_blank">Developer</a></p>
	  	</div>
	  	<div class="toggleNav">Novelty Soundbytes</div>
	  	<div class="leftNavContent">
	  		<p><a href="http://www.sixstrangetales.com" target="_blank">Six Strange Tales</a></p>
	  		<p><a href="http://www.noveltysoundbytes.com/blogOsphere/" target="_blank">blogOsphere</a></p>
	  	</div>
	  	<div class="toggleNav">Tech Profile</div>
	  	<div class="leftNavContent">
	  		<p><a href="http://www.spafinder.com/" target="_blank">Spafinder</a></p>
	  		<p><a href="http://www.security.honeywell.com/" target="_blank">Honeywell</a></p>
	  		<p><a href="http://www.leapnyc.org" target="_blank">LEAP</a></p>
	  		<p><a href="http://www.campusfood.com/" target="_blank">Campusfood</a></p>
	  		<p><a href="http://www.fhlbny.com/" target="_blank">Federal Home Loan Bank</a></p>
	  		<p><a href="http://www.nyse.com/" target="_blank">New York Stock Exchange</a></p>
	  	</div>
	  	<div class="toggleNav">Marketing Clients</div>
	  	<div class="leftNavContent">
	  		<p><a href="http://www.superbookdeals.com/cgi-bin/home.cgi" target="_blank">Super Book Deals</a></p>
	  		<p><a href="http://euescreengems.com/" target="_blank">Screen Gems</a></p>
	  		<p><a href="http://www.warnerbros.com/" target="_blank">Warner Bros.</a></p>
	  		<p><a href="http://www.wmg.com/" target="_blank">Warner Music Group</a></p>
	  		<p><a href="http://oilfactory.com/" target="_blank">Oil Factory</a></p>
	  		<p><a href="http://www.kmart.com/" target="_blank">Kmart</a></p>
	  		<p><a href="http://shop.tommyboy.com/store.asp" target="_blank">Tommy Boy Records</a></p>
	  		<p><a href="http://www.davematthewsband.com/" target="_blank">Dave Mathews Band</a></p>
	  		<p><a href="http://msn.foxsports.com/nhl" target="_blank">NHL FOX</a></p>
	  		<p><a href="http://www.rcarecords.com/" target="_blank">Jive Records</a></p>
	  	</div>
	</div>
</nav>	