	<footer>	
		<div class="footer">
			<ul>
					<li><a href="/tech/">Home &nbsp; &bull;</a></li> 
					<li><a href="/tech/profile">Company Profile</a> &nbsp; &bull;</li>
					<li><a href="/tech/profile/marketing">Marketing Profile</a> &nbsp; &bull;</li>
					<li><a href="http://www.noveltysoundbytes.com/blogOsphere">blogOsphere</a></li>
			</ul>
			<hr size="2" />  
			<p>Tech Stuffs courtesy of nSb Web. &copy; Copyright 2012. All rights reserved.</p>
		</div>
	</footer>		  
	<!-- Javascript -------------->
	<script src="<?php echo $this->baseURL('/cdn/jQuery/jQuery.js'); ?>"></script>
	<script src="http://cdn.jquerytools.org/1.2.5/full/jquery.tools.min.js"></script><!-- Curve -->
	<!-- Javascript -------------->