<section id="curveIntro">
	<h1>Staying Ahead of the Curve</h1> 
	<p>Welcome, this is an amalgam of samples, code snippets and need to knows in regards to best practices for Front-End coding.</p>
	<p>The topics within are related to HTML5, CSS3 and jQuery.</p>
	<p>It's a comprehensive approach to documenting current supported practices using these front-end technologies.
		Basically, this is a one stop shop where I will be depositing new finds and updating coding techniques for my own use. 
		If you find yourself here and learn something or are reminded of something useful then your welcome. 
		If you care to chat about some of the topics written here and would like to discuss, shoot on over to the 
		<b><a href="/blogosphere/">blogOsphere</a></b> and leave a comment. I'll open a thread just for those of you who are interested in doing so.</p>
	<p>Just a bit of information you may find useful when navigating, use the arrow keys!!
	<p class="sign">- R. Lewis, Developer</p>
</section>
