				<div class="page"> 
	 				<div class="navi"></div> <!-- page #3 -->
	 					<div class="scrollable"> <!-- inner scrollable #3 --> 
	 						<div class="items"> <!-- root element for scrollable items --> 
	 							<div class="item"> <!-- items on the first page -->
									<img src="http://farm4.static.flickr.com/3155/2636513939_cd75b704ec.jpg" /> 
									<p>CSS3 - Progessive Enhancement</p> 
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/progressiveEnhancement.phtml';?>
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/stylings.phtml';?>
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/toolBoxes.phtml';?>
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/animation.phtml';?>
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/webFonts.phtml';?>
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/mediaQueries.phtml';?>
								</div> 
								<div class="item"> 
									<?php include_once 'page3_css3/browserSupport.phtml';?>
								</div> 
	 						</div> 
	 					</div> 
	 				</div> 