				<div class="page"> 
	 				<div class="navi"></div> <!-- page #4 -->
	 					<div class="scrollable"> <!-- inner scrollable #3 --> 
	 						<div class="items"> <!-- root element for scrollable items --> 
	 							<div class="item"> <!-- items on the first page -->
									<img src="http://farm4.static.flickr.com/3155/2636513939_cd75b704ec.jpg" /> 
									<p>jQuery</p> 
								</div> 
								<div class="item"> 
									<p>Staying Ahead of the Curve is built in jQuery. Documentation has stopped due to site development. Stay tuned.</p>
								</div> 
	 						</div> 
	 					</div> 
	 				</div> 