				<div class="page"> <!-- page #2 -->
	 				<div class="navi"></div> 
 					<div class="scrollable"><!-- inner scrollable #2 --> 
 						<div class="items"> <!-- root element for scrollable items -->
		 					<div class="item"> <!-- items on the second page -->
								<img src="http://farm1.static.flickr.com/143/321464099_a7cfcb95cf.jpg" /> 
								<p>Use the arrow keys or click the dot switchs above to navigate.</p> 
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/HTML5.phtml';?>
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/HTML5_2.phtml'; ?>
							</div> 
							<div class="item">
								<?php include_once 'page2_html5/funFacts.phtml';?> 
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/articles.phtml';?>
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/aria.phtml';?>
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/roles.phtml';?>
							</div> 
							<div class="item">
								<?php include_once 'page2_html5/forms.phtml';?>
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/semantic.phtml';?>
							</div> 
							<div class="item"> 
								<?php include_once 'page2_html5/video.phtml';?>
							</div> 
	 					</div> 
	 				</div>
	 			</div>
		 			