			<div class="page"> <!-- page #1 -->
	 			<div class="navi"></div> <!-- sub navigator #1 --> 
	 				<div class="scrollable"><!-- inner scrollable #1 -->  
	 					<div class="items"> <!-- root element for scrollable items --> 
	 						<div class="item"> <!-- items  --> 
								<img src="http://farm1.static.flickr.com/114/299183878_4feac12b04.jpg" />
								<p>Staying Ahead of the Curve</p> 
							</div> 
							<div class="item"> 
								<?php include_once 'curveIntro.phtml';?>
							</div> 
	 					</div> 
	 				</div> 
	 			</div> 