<article id="funFacts">
	<h2>More fun facts:</h2>
	<p>Each Section tag in html5, in theory, can have it's own h1, h2 etc tags. Same rule applies to article tags.
		H tags can be combined into groups, or hgroups to keep in consistency with robots and crawlers and in essence hide h tags within the group or section.
		HTML5 was created by developers from Opera, Mozilla (Firefox) and Apple as a replacement for xhtml and xhtml2.
		It is designed to be backwards compatible with html 4 and lower as well as xhtml.
		In HTML5, sections, articles and the sort all but replace div's, if you can imagine that.
		It consists of markup language and an API aspect for web applications (think gmail).</p>
	<p>Samples - <a href="http://www.html5rocks.com" target="_blank">http://www.html5rocks.com</a></p>
</article>
<section id="htmlSnippet">
	<p>Here is a snippet of the Boilerplate type html tag used for IE browser specific styling as well as non-javascript browsers.</p>
	<textarea rows="5" cols="75" readonly>
		<!--[if lt IE 7]> <html lang="en-us" class="no-js ie6"> <![endif]-->
		<!--[if IE 7]>    <html lang="en-us" class="no-js ie7"> <![endif]-->
		<!--[if IE 8]>    <html lang="en-us" class="no-js ie8"> <![endif]-->
		<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
	</textarea>
</section>