<article id="html5_2">
		<p>Some say that validation is not always necessary for a well functioning site. Though I disagree with the sentiment, technically speaking this is true. When building a page you should always seek to have it validate. Only add items you know for sure will not compromise the site. In the event you are aware that an item will cause the page to not validate use best practices. If you do not know in advance that something will not validate or whether or not you can 'live with it', don't add it to the page. It's probabley not semantically correct. There are instances, such as ARIA roles which may not validate, however, their purpose (makes sites more accessible to those with disabilities) is worth the validation warning.</p>
		<p>Of couse if you'd like to take a peak at this source code, you can at any time because, guess what? It's full on HTML5</p>
		<p>Sections and sub-sections become identifiable as sections and would need to be styled with this in mind. Be aware of specificity when styling section elements. For instance, you cannot style a header element in IE8. What you can do is further define the tag using ARIA role attributes, ex:[roll=banner]. In IE7, you would need to further extend the element by using a class such as .header. </p>
</article>

<section id="crossBrowser">
	<h2>Check Current Browser Compatibility</h2>
	<p>See how your favorite browser stands up to the HTML5 compatibility test!</p>
	<p><a href="http://html5test.com/" target="_blank">HTML5 Browser Test</a></p>
	<p> Now test your code with: <a href="http://validator.w3.org/unicorn/" target="_blank"> W3C UNICORN Validator</a></p>
</section>  