<section id="roles">
	<h2>Widget roles include:</h2>
	<ul>
		<li>alert - </li>
		<li>alertdialog - </li>
		<li>button - </li>
		<li>checkbox - </li>
		<li>combobox - </li>
		<li>marquee - </li>
		<li>menuitem - </li>
		<li>menuitemcheckbox - </li>
		<li>menuitemradio - </li>
		<li>option - </li>
		<li>progressbar - </li>
		<li>radio - </li>
		<li>scrollbar - </li>
		<li>slider - </li>
		<li>spinbutton - </li>
		<li>status - </li>
		<li>tab - </li>
		<li>tabpanel - </li>
		<li>textbox - </li>
		<li>timer - </li>
		<li>tooltip - </li>
		<li>treeitem</li>
	</ul>
	<h2>Landmark roles include:</h2>
	<ul>
		<li>banner - </li>
		<li>complementary - </li>
		<li>contentinfo - </li>
		<li>main - </li>
		<li>navigation - </li>
		<li>search</li>
	</ul>
	<h2>Document structure roles include:</h2>
	<ul>
		<li>article - </li>
		<li>group - </li>
		<li>heading - </li>
		<li>list - </li>
		<li>listitem - </li>
		<li>note</li>
		<li>presentation</li>
		<li>separator</li>
	</ul>
</section>