<div class="rightBox txt">
	 <h2>Marketing Profile</h2>
   <p>Recently nSb entered into an agreement with Kindle and the good people at Crackerhouse Publishing Intl. and branched off into the world of eBook publishing.</p>
   <p>The first exciting title under nSb publishing LLC. is <i>Six Strange Tales</i> by author Individual Eleven. Future titles include <i>The Religious Argument: Web Design vs Web Development</i>, <i>Cooking with Camille: Yummy Recipes</i> and <i>Molly Kills Kong</i>.</p>
   <hr size="2" />
   <p>Novelty Soundbytes originated evolving from the world of music, film and television. A few notable clients we've worked with include:</p>
   <?=$this->other; ?>
   <hr size="2" />
   <p>Other more web based affiliates include:</p>
   <?=$this->companies; // get data object from controller?>
</div>
<div class="rightBox">
	 <div class="rightSubBox left">
	 	<a href="http://bit.ly/w3gCW4" target="_blank">
	 		<img class="burst" src="../cdn/images/burstOrderNow.png" width=82 height=82 alt="Order NOW" title="Order NOW" border=0 />
	 	</a>
	 	<img src="../cdn/images/6SThtmlEmail.png" width=215 height=242 alt="Six Strange Tales" title="Six Strange Tales" border=0 />
  </div>
	 <div class="rightSubBox right">
	 	<a href="http://kindlingleaders.wordpress.com/about-2/project-kindle/" target="_blank">
	 		<img src="../cdn/images/projectKindle.jpg" width=215 height=111 alt="Read about Project Kindle's Cost Free Children Services" title="Read about Project Kindle's Cost Free Children Services" border=0 />
	 	</a>
  </div>
	 <div class="rightSubBox right">
			<a href="http://bit.ly/w3gCW4" target="_blank">
				<img src="../cdn/images/barnes_noble.png" width=215 height=111 alt="nSb publishing, LLC in partnership with Barnes &amp; Nobles" title="nSb publishing, LLC in partnership with Barnes &amp; Nobles" border=0 />
	 		</a>
	 </div>
	 <div class="rightSubBox full">
	 		<iframe width="450" height="340" src="http://www.youtube.com/embed/PgMp3we7Y5I" frameborder="0" allowfullscreen></iframe>
  </div>
</div>