<section id="browser_support">
	<h1>Browser Support</h1>
	<p>Progressive enhancement is a great way to go as far as how to ensure usability and great user experience. CSS3 is coming along but there are differences 
	in browsers support. Javascript libraries such as Dean Edwards IE7.js, IE-CSS3.js and eCSSTender help render css3 so that the different selectors and attributes
	display evenly accross all browsers.</p>
	<p>ex:</p>
	<p>comment [if it IE9] end comment <br /><br />Dean Edwards IE7.js <br /><br />comment [end if] end comment</p>
	<p>One could also serve a PIE.htc file from the server and set behavior:url(path/to/PIE.htc). Any of these methods will give more sophisicated CSS3 display 
	in older browsers. It also may NOT be worth the effort in many cases which in the end is a personal or corporate choice. The suggested way to go
	would be to accept the fact that not all browsers  support CSS3 and design with this in mind.</p>
	<p>Some of the more common CSS3 values accepted in most browsers (atleast the modern ones) are:
	<ul>
		<li>box-shadow &bull; </li>
		<li>border-radius &bull; </li>
		<li>multiple-backgrounds &bull; </li>
		<li>background-image &bull; </li>
		<li>svg-backgrounds &bull; </li>
		<li>@font-face</li>
	</ul>
</section>