<section id="progressive_enhancement">
	<h2>Progressive Enhancement</h2>
	<p>The concept of progressive enhancement is basic in essence. Modern browsers use modern features where by older browsers 
	may not use some of the nuances of CSS3 or HTML5. Therefore, progessive enhancement best practices suggest designing for both
	older and modern browsers with predictable outcomes. For instance, IE 9 may support the latest and greatest in CSS3, IE 7 
	may not. CSS3 may present some really cool effect and so we implement keeping in mind that this effect will not be 
	present in IE7. The look of IE7 should still be 'A Grade'. However, if a user were to upgrade her browser she would immediately
	notice the cooler effects in the IE9 browser. This is progressive enhancement. Designing and coding as a feature using 
	thet latest and greatest in CSS3 or HTML5 coding keeping in mind older browsers which do not support.</p> 
	<p>CSS3 is used widely by modern browsers (Safari, Chrome, Firefox, iOS and Android), however, not so much by 
	IE 7 and IE8. IE 9 does use CSS3 for the most part but it's a much less used browser. As time progresses these browsers
	will use CSS3 more and more as the older versions of these browsers fade. Correct implementation of CSS3 is to use it as a feature.
	The fact that it is not used in older browsers should not be considered a bug. These browsers will catch up in time. Until then, 
	CSS3 will remain a feature that exists in some browsers and not in others.</p>
	<p>CSS3 can be used to create images and even animation. If used correctly it can be used and displayed in modern browsers
	bypassing older browsers as still images. If the user were to upgrade to the highest version of any particular browser
	css3 would automatically work (giving immediate gratification for the user).</p>
</section>