<section id="text_properties">
	<h2>Toolboxes</h2>
	<p>There are some really cool toolboxes out there tha I like to use quite often for gradients, transitions and animations. Here are two of my favorites:</p>
	<p><a href="http://www.westciv.com/tools/text-properties/index.html" target="_blank">Style Master</a><br />
		<a href="http://gradients.glrzad.com/" target="_blank">CSS3 Gradient Generator</a></p>
	<p>And since we are going outside the box I'll throw in a cool favicon generator by Dynamic Drive:</p>
	<p><a href="http://tools.dynamicdrive.com/favicon/" target="_blank">Favicon Generator</a></p>
</section>
<section id="gradients">
	<div class="gradient">
		<h3>Gradients</h3>
		<p>Here is an example of gradients.It only appears as a progressive enhancement feature in firefox 
			however, could be implemented for any browser which support gradients. The gradient generator above actually 
			gives code for all browsers successfully.</p>
	</div>
</section>
<section id="animations">
		<h3>Transitions Effects - Only in Chrome (:P)</h3> 
		<div id="slideShow"> 
 			<div id="slide1" class="slide"> 
 				<h2>Kindle</h2> 
 				<h3>Six Strange Tales</h3> 
 			</div> 
 			<div id="slide2" class="slide"> 
 				<h2>Nook</h2> 
 				<h3>Six Strange Tales</h3> 
 			</div> 
 		</div>
</section>